//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyStoreEntities3 : DbContext
    {
        public MyStoreEntities3()
            : base("name=MyStoreEntities3")
        {
        }
        public MyStoreEntities3(string connectionString) : base("name=MyStoreEntities3") {
            this.Database.Connection.ConnectionString = connectionString;
        }
        public (bool, string) TestConnection()
        {
            try
            {
                Database.Connection.Open();
                Database.Connection.Close();
            }
            catch (Exception ex)
            {
                return (false, ex.Message);
            }
            return (true, "Connection is OK");
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual DbSet<PurchaseStatusEnum> PurchaseStatusEnums { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
    }
}
