//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Photo_Id { get; set; }
        public byte[] Data { get; set; }
        public Nullable<int> Product_id { get; set; }
    
        public virtual Photo Photo1 { get; set; }
        public virtual Photo Photo2 { get; set; }
        public virtual Product Product { get; set; }
    }
}
